Repository UBC-MDS/DSCI-532_2024_18_VancouverAirbnbPrices, pull requests merged in 2024-04, with the labels that each got.

#28 19 milestone2 updating framework for input widgets and output figures
  app.py
  assets/house_icon.png
  assets/texts.py
  index.py
  menu.py
  pages/credentials.py
  pages/observation.py
Labels: enhancement

#34 Addition of summary stats
  pages/observation.py
Labels: enhancement

#33 Added a map
  pages/observation.py
Labels: enhancement

#57 changed summary stat cards
  pages/credentials.py
  pages/observation.py
  src/bar_graph.py
  src/make_cards.py
Labels: enhancement

#62 updated neighbourhood to select for multiple values
  pages/observation.py
Labels: enhancement

#60 51 improve map
  pages/observation.py
  src/map.py
Labels: enhancement

#68 61 prediction design
  pages/observation.py
  pages/prediction.py
  src/map.py
Labels: enhancement

#70 added m3 reflection
  reports/m3-reflection.md
Labels: documentation

#84 83 add default map
  pages/observation.py
Labels: bug

#90 Added milestone 4 reflection
  reports/m4-reflection.md
Labels: documentation
